/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Espace_technicien (void)
{
  GtkWidget *Espace_technicien;
  GtkWidget *fixed1;
  GtkWidget *vseparator1;
  GtkWidget *eventbox6;
  GtkWidget *deconnecterET;
  GtkWidget *alignment14;
  GtkWidget *hbox13;
  GtkWidget *image20;
  GtkWidget *label40;
  GtkWidget *eventbox7;
  GtkWidget *labelET;
  GtkWidget *eventbox77;
  GtkWidget *affichercapteur;
  GtkWidget *alignment15;
  GtkWidget *hbox14;
  GtkWidget *image21;
  GtkWidget *eventbox76;
  GtkWidget *label41;
  GtkWidget *eventbox86;
  GtkWidget *ajouterc;
  GtkWidget *eventbox9;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *eventbox3;
  GtkWidget *image2;
  GtkWidget *labelac;
  GtkWidget *eventbox87;
  GtkWidget *modifierc;
  GtkWidget *eventbox1;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *labelmc;
  GtkWidget *eventbox88;
  GtkWidget *supprimerc;
  GtkWidget *eventbox4;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *labelsc;
  GtkWidget *eventbox89;
  GtkWidget *chercherc;
  GtkWidget *eventbox8;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *eventbox2;
  GtkWidget *labelcc;
  GtkWidget *imageE_T;
  GtkWidget *eventbox92;
  GtkWidget *scrolledwindow3;
  GtkWidget *treeviewaffcapteur;

  Espace_technicien = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_technicien), _("Espace_Technicien"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Espace_technicien), fixed1);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator1, 984, 56);
  gtk_widget_set_size_request (vseparator1, 16, 16);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox6, 16, 16);
  gtk_widget_set_size_request (eventbox6, 120, 29);

  deconnecterET = gtk_button_new ();
  gtk_widget_show (deconnecterET);
  gtk_container_add (GTK_CONTAINER (eventbox6), deconnecterET);
  gtk_widget_set_size_request (deconnecterET, 120, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (deconnecterET), alignment14);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox13);

  image20 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox13), image20, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Deconnecter"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox13), label40, FALSE, FALSE, 0);

  eventbox7 = gtk_event_box_new ();
  gtk_widget_show (eventbox7);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox7, 488, 40);
  gtk_widget_set_size_request (eventbox7, 248, 63);

  labelET = gtk_label_new (_("Espace Technicien"));
  gtk_widget_show (labelET);
  gtk_container_add (GTK_CONTAINER (eventbox7), labelET);
  gtk_widget_set_size_request (labelET, 248, 63);

  eventbox77 = gtk_event_box_new ();
  gtk_widget_show (eventbox77);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox77, 72, 152);
  gtk_widget_set_size_request (eventbox77, 106, 56);

  affichercapteur = gtk_button_new ();
  gtk_widget_show (affichercapteur);
  gtk_container_add (GTK_CONTAINER (eventbox77), affichercapteur);
  gtk_widget_set_size_request (affichercapteur, 106, 56);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (affichercapteur), alignment15);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox14);

  image21 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox14), image21, FALSE, FALSE, 0);

  eventbox76 = gtk_event_box_new ();
  gtk_widget_show (eventbox76);
  gtk_box_pack_start (GTK_BOX (hbox14), eventbox76, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label41);
  gtk_container_add (GTK_CONTAINER (eventbox76), label41);

  eventbox86 = gtk_event_box_new ();
  gtk_widget_show (eventbox86);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox86, 232, 368);
  gtk_widget_set_size_request (eventbox86, 168, 45);

  ajouterc = gtk_button_new ();
  gtk_widget_show (ajouterc);
  gtk_container_add (GTK_CONTAINER (eventbox86), ajouterc);
  gtk_widget_set_size_request (ajouterc, 168, 45);
  gtk_button_set_focus_on_click (GTK_BUTTON (ajouterc), FALSE);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_container_add (GTK_CONTAINER (ajouterc), eventbox9);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (eventbox9), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_box_pack_start (GTK_BOX (hbox1), eventbox3, FALSE, FALSE, 0);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (eventbox3), image2);

  labelac = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (labelac);
  gtk_box_pack_start (GTK_BOX (hbox1), labelac, FALSE, FALSE, 0);

  eventbox87 = gtk_event_box_new ();
  gtk_widget_show (eventbox87);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox87, 520, 368);
  gtk_widget_set_size_request (eventbox87, 192, 45);

  modifierc = gtk_button_new ();
  gtk_widget_show (modifierc);
  gtk_container_add (GTK_CONTAINER (eventbox87), modifierc);
  gtk_widget_set_size_request (modifierc, 192, 45);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (modifierc), eventbox1);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (eventbox1), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  labelmc = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (labelmc);
  gtk_box_pack_start (GTK_BOX (hbox2), labelmc, FALSE, FALSE, 0);

  eventbox88 = gtk_event_box_new ();
  gtk_widget_show (eventbox88);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox88, 232, 456);
  gtk_widget_set_size_request (eventbox88, 168, 45);

  supprimerc = gtk_button_new ();
  gtk_widget_show (supprimerc);
  gtk_container_add (GTK_CONTAINER (eventbox88), supprimerc);
  gtk_widget_set_size_request (supprimerc, 168, 45);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_container_add (GTK_CONTAINER (supprimerc), eventbox4);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (eventbox4), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  labelsc = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (labelsc);
  gtk_box_pack_start (GTK_BOX (hbox3), labelsc, FALSE, FALSE, 0);

  eventbox89 = gtk_event_box_new ();
  gtk_widget_show (eventbox89);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox89, 520, 456);
  gtk_widget_set_size_request (eventbox89, 192, 45);

  chercherc = gtk_button_new ();
  gtk_widget_show (chercherc);
  gtk_container_add (GTK_CONTAINER (eventbox89), chercherc);
  gtk_widget_set_size_request (chercherc, 192, 45);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_container_add (GTK_CONTAINER (chercherc), eventbox8);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (eventbox8), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_box_pack_start (GTK_BOX (hbox4), eventbox2, FALSE, FALSE, 0);

  labelcc = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (labelcc);
  gtk_container_add (GTK_CONTAINER (eventbox2), labelcc);

  imageE_T = create_pixmap (Espace_technicien, "capteur-air-citoyen.jpg");
  gtk_widget_show (imageE_T);
  gtk_fixed_put (GTK_FIXED (fixed1), imageE_T, 0, 0);
  gtk_widget_set_size_request (imageE_T, 1296, 616);

  eventbox92 = gtk_event_box_new ();
  gtk_widget_show (eventbox92);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox92, 208, 112);
  gtk_widget_set_size_request (eventbox92, 960, 216);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (eventbox92), scrolledwindow3);
  gtk_widget_set_size_request (scrolledwindow3, 960, 216);

  treeviewaffcapteur = gtk_tree_view_new ();
  gtk_widget_show (treeviewaffcapteur);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), treeviewaffcapteur);
  gtk_widget_set_size_request (treeviewaffcapteur, 960, 216);

  g_signal_connect ((gpointer) deconnecterET, "clicked",
                    G_CALLBACK (on_deconnecterET_clicked),
                    NULL);
  g_signal_connect ((gpointer) affichercapteur, "clicked",
                    G_CALLBACK (on_affichercapteur_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouterc, "clicked",
                    G_CALLBACK (on_ajouterc_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifierc, "clicked",
                    G_CALLBACK (on_modifierc_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimerc, "clicked",
                    G_CALLBACK (on_supprimerc_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercherc, "clicked",
                    G_CALLBACK (on_chercherc_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeviewaffcapteur, "row_activated",
                    G_CALLBACK (on_treeviewaffcapteur_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_technicien, Espace_technicien, "Espace_technicien");
  GLADE_HOOKUP_OBJECT (Espace_technicien, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Espace_technicien, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (Espace_technicien, deconnecterET, "deconnecterET");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image20, "image20");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label40, "label40");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (Espace_technicien, labelET, "labelET");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox77, "eventbox77");
  GLADE_HOOKUP_OBJECT (Espace_technicien, affichercapteur, "affichercapteur");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image21, "image21");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox76, "eventbox76");
  GLADE_HOOKUP_OBJECT (Espace_technicien, label41, "label41");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox86, "eventbox86");
  GLADE_HOOKUP_OBJECT (Espace_technicien, ajouterc, "ajouterc");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image2, "image2");
  GLADE_HOOKUP_OBJECT (Espace_technicien, labelac, "labelac");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox87, "eventbox87");
  GLADE_HOOKUP_OBJECT (Espace_technicien, modifierc, "modifierc");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image3, "image3");
  GLADE_HOOKUP_OBJECT (Espace_technicien, labelmc, "labelmc");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox88, "eventbox88");
  GLADE_HOOKUP_OBJECT (Espace_technicien, supprimerc, "supprimerc");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image4, "image4");
  GLADE_HOOKUP_OBJECT (Espace_technicien, labelsc, "labelsc");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox89, "eventbox89");
  GLADE_HOOKUP_OBJECT (Espace_technicien, chercherc, "chercherc");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (Espace_technicien, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Espace_technicien, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Espace_technicien, image5, "image5");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (Espace_technicien, labelcc, "labelcc");
  GLADE_HOOKUP_OBJECT (Espace_technicien, imageE_T, "imageE_T");
  GLADE_HOOKUP_OBJECT (Espace_technicien, eventbox92, "eventbox92");
  GLADE_HOOKUP_OBJECT (Espace_technicien, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (Espace_technicien, treeviewaffcapteur, "treeviewaffcapteur");

  return Espace_technicien;
}

GtkWidget*
create_modifier_capteur (void)
{
  GtkWidget *modifier_capteur;
  GtkWidget *fixed2;
  GtkWidget *entryidm;
  GtkWidget *entryvaleurm;
  GtkWidget *eventbox26;
  GtkWidget *labeldatem;
  GtkObject *spinbuttonjourm_adj;
  GtkWidget *spinbuttonjourm;
  GtkObject *spinbuttonmoism_adj;
  GtkWidget *spinbuttonmoism;
  GtkObject *spinbuttonanneem_adj;
  GtkWidget *spinbuttonanneem;
  GtkWidget *eventbox27;
  GtkWidget *labelvaleurm;
  GtkWidget *eventbox28;
  GtkWidget *labelidm;
  GtkWidget *eventbox29;
  GtkWidget *labelmodifiercapteur;
  GtkWidget *eventbox30;
  GtkWidget *labelanneem;
  GtkWidget *eventbox31;
  GtkWidget *labelmoism;
  GtkWidget *eventbox32;
  GtkWidget *labeljourm;
  GtkWidget *label29;
  GtkWidget *eventbox33;
  GtkWidget *labelaffichagem;
  GtkWidget *vseparator2;
  GtkWidget *eventbox59;
  GtkWidget *labelmarquem;
  GtkWidget *eventbox60;
  GtkWidget *comboboxm;
  GtkWidget *eventbox61;
  GtkWidget *labeltypem;
  GtkWidget *eventbox62;
  GtkWidget *rb1;
  GSList *rb1_group = NULL;
  GtkWidget *eventbox63;
  GtkWidget *rb2;
  GtkWidget *eventbox64;
  GtkWidget *rb3;
  GtkWidget *eventbox65;
  GtkWidget *rb4;
  GtkWidget *eventbox66;
  GtkWidget *rb5;
  GtkWidget *eventbox67;
  GtkWidget *confmodf;
  GtkWidget *eventbox73;
  GtkWidget *labelverifexiste;
  GtkWidget *eventbox78;
  GtkWidget *buttonannulerm;
  GtkWidget *annulerm;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *label;
  GtkWidget *eventbox79;
  GtkWidget *verifierexiste;
  GtkWidget *alignment17;
  GtkWidget *hbox15;
  GtkWidget *image22;
  GtkWidget *label42;
  GtkWidget *eventbox85;
  GtkWidget *confirmerm;
  GtkWidget *eventbox34;
  GtkWidget *alignment7;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *eventbox84;
  GtkWidget *label27;
  GtkWidget *image7;

  modifier_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_capteur), _("modifier"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (modifier_capteur), fixed2);

  entryidm = gtk_entry_new ();
  gtk_widget_show (entryidm);
  gtk_fixed_put (GTK_FIXED (fixed2), entryidm, 272, 144);
  gtk_widget_set_size_request (entryidm, 176, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidm), 8226);

  entryvaleurm = gtk_entry_new ();
  gtk_widget_show (entryvaleurm);
  gtk_fixed_put (GTK_FIXED (fixed2), entryvaleurm, 296, 432);
  gtk_widget_set_size_request (entryvaleurm, 160, 33);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryvaleurm), 8226);

  eventbox26 = gtk_event_box_new ();
  gtk_widget_show (eventbox26);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox26, 104, 376);
  gtk_widget_set_size_request (eventbox26, 80, 32);

  labeldatem = gtk_label_new (_("date"));
  gtk_widget_show (labeldatem);
  gtk_container_add (GTK_CONTAINER (eventbox26), labeldatem);
  gtk_widget_set_size_request (labeldatem, 80, 32);

  spinbuttonjourm_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonjourm = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjourm_adj), 1, 0);
  gtk_widget_show (spinbuttonjourm);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonjourm, 312, 384);
  gtk_widget_set_size_request (spinbuttonjourm, 60, 27);

  spinbuttonmoism_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmoism = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmoism_adj), 1, 0);
  gtk_widget_show (spinbuttonmoism);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonmoism, 480, 384);
  gtk_widget_set_size_request (spinbuttonmoism, 60, 27);

  spinbuttonanneem_adj = gtk_adjustment_new (2021, 2010, 2021, 1, 10, 10);
  spinbuttonanneem = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonanneem_adj), 1, 0);
  gtk_widget_show (spinbuttonanneem);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttonanneem, 624, 384);
  gtk_widget_set_size_request (spinbuttonanneem, 88, 27);

  eventbox27 = gtk_event_box_new ();
  gtk_widget_show (eventbox27);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox27, 104, 432);
  gtk_widget_set_size_request (eventbox27, 80, 32);

  labelvaleurm = gtk_label_new (_("valeur"));
  gtk_widget_show (labelvaleurm);
  gtk_container_add (GTK_CONTAINER (eventbox27), labelvaleurm);
  gtk_widget_set_size_request (labelvaleurm, 80, 32);

  eventbox28 = gtk_event_box_new ();
  gtk_widget_show (eventbox28);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox28, 80, 152);
  gtk_widget_set_size_request (eventbox28, 136, 33);

  labelidm = gtk_label_new (_("Identifiant"));
  gtk_widget_show (labelidm);
  gtk_container_add (GTK_CONTAINER (eventbox28), labelidm);
  gtk_widget_set_size_request (labelidm, 136, 33);

  eventbox29 = gtk_event_box_new ();
  gtk_widget_show (eventbox29);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox29, 328, 24);
  gtk_widget_set_size_request (eventbox29, 208, 72);

  labelmodifiercapteur = gtk_label_new (_("Modifier un capteur"));
  gtk_widget_show (labelmodifiercapteur);
  gtk_container_add (GTK_CONTAINER (eventbox29), labelmodifiercapteur);
  gtk_widget_set_size_request (labelmodifiercapteur, 208, 72);

  eventbox30 = gtk_event_box_new ();
  gtk_widget_show (eventbox30);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox30, 552, 384);
  gtk_widget_set_size_request (eventbox30, 49, 17);

  labelanneem = gtk_label_new (_("annee"));
  gtk_widget_show (labelanneem);
  gtk_container_add (GTK_CONTAINER (eventbox30), labelanneem);
  gtk_widget_set_size_request (labelanneem, 49, 17);

  eventbox31 = gtk_event_box_new ();
  gtk_widget_show (eventbox31);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox31, 408, 384);
  gtk_widget_set_size_request (eventbox31, 49, 17);

  labelmoism = gtk_label_new (_("Mois"));
  gtk_widget_show (labelmoism);
  gtk_container_add (GTK_CONTAINER (eventbox31), labelmoism);
  gtk_widget_set_size_request (labelmoism, 49, 17);

  eventbox32 = gtk_event_box_new ();
  gtk_widget_show (eventbox32);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox32, 248, 384);
  gtk_widget_set_size_request (eventbox32, 49, 17);

  labeljourm = gtk_label_new (_("Jour"));
  gtk_widget_show (labeljourm);
  gtk_container_add (GTK_CONTAINER (eventbox32), labeljourm);
  gtk_widget_set_size_request (labeljourm, 49, 17);

  label29 = gtk_label_new ("");
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed2), label29, 168, 520);
  gtk_widget_set_size_request (label29, 49, 17);

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox33, 112, 512);
  gtk_widget_set_size_request (eventbox33, 312, 33);

  labelaffichagem = gtk_label_new ("");
  gtk_widget_show (labelaffichagem);
  gtk_container_add (GTK_CONTAINER (eventbox33), labelaffichagem);
  gtk_widget_set_size_request (labelaffichagem, 312, 33);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed2), vseparator2, 552, 320);
  gtk_widget_set_size_request (vseparator2, 16, 16);

  eventbox59 = gtk_event_box_new ();
  gtk_widget_show (eventbox59);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox59, 104, 232);
  gtk_widget_set_size_request (eventbox59, 80, 32);

  labelmarquem = gtk_label_new (_("Marque"));
  gtk_widget_show (labelmarquem);
  gtk_container_add (GTK_CONTAINER (eventbox59), labelmarquem);
  gtk_widget_set_size_request (labelmarquem, 80, 32);

  eventbox60 = gtk_event_box_new ();
  gtk_widget_show (eventbox60);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox60, 272, 296);
  gtk_widget_set_size_request (eventbox60, 208, 39);

  comboboxm = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxm);
  gtk_container_add (GTK_CONTAINER (eventbox60), comboboxm);
  gtk_widget_set_size_request (comboboxm, 208, 39);
  gtk_container_set_border_width (GTK_CONTAINER (comboboxm), 1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxm), _("capteur_de_Mouvement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxm), _("capteur_de_Fumee"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxm), _("capteur_de_Debit_deau"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxm), _("capteur_de_Temperature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxm), _("Balance"));

  eventbox61 = gtk_event_box_new ();
  gtk_widget_show (eventbox61);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox61, 104, 296);
  gtk_widget_set_size_request (eventbox61, 80, 32);

  labeltypem = gtk_label_new (_("Type"));
  gtk_widget_show (labeltypem);
  gtk_container_add (GTK_CONTAINER (eventbox61), labeltypem);
  gtk_widget_set_size_request (labeltypem, 80, 32);

  eventbox62 = gtk_event_box_new ();
  gtk_widget_show (eventbox62);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox62, 216, 240);
  gtk_widget_set_size_request (eventbox62, 96, 24);

  rb1 = gtk_radio_button_new_with_mnemonic (NULL, _("CHERRY"));
  gtk_widget_show (rb1);
  gtk_container_add (GTK_CONTAINER (eventbox62), rb1);
  gtk_widget_set_size_request (rb1, 96, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb1), rb1_group);
  rb1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb1));

  eventbox63 = gtk_event_box_new ();
  gtk_widget_show (eventbox63);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox63, 328, 240);
  gtk_widget_set_size_request (eventbox63, 80, 24);

  rb2 = gtk_radio_button_new_with_mnemonic (NULL, _("NEDO"));
  gtk_widget_show (rb2);
  gtk_container_add (GTK_CONTAINER (eventbox63), rb2);
  gtk_widget_set_size_request (rb2, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb2), rb1_group);
  rb1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb2));

  eventbox64 = gtk_event_box_new ();
  gtk_widget_show (eventbox64);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox64, 416, 240);
  gtk_widget_set_size_request (eventbox64, 144, 24);

  rb3 = gtk_radio_button_new_with_mnemonic (NULL, _("MICRO-EPSILON"));
  gtk_widget_show (rb3);
  gtk_container_add (GTK_CONTAINER (eventbox64), rb3);
  gtk_widget_set_size_request (rb3, 144, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb3), rb1_group);
  rb1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb3));

  eventbox65 = gtk_event_box_new ();
  gtk_widget_show (eventbox65);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox65, 568, 240);
  gtk_widget_set_size_request (eventbox65, 80, 24);

  rb4 = gtk_radio_button_new_with_mnemonic (NULL, _("BOSCH"));
  gtk_widget_show (rb4);
  gtk_container_add (GTK_CONTAINER (eventbox65), rb4);
  gtk_widget_set_size_request (rb4, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb4), rb1_group);
  rb1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb4));

  eventbox66 = gtk_event_box_new ();
  gtk_widget_show (eventbox66);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox66, 672, 240);
  gtk_widget_set_size_request (eventbox66, 136, 24);

  rb5 = gtk_radio_button_new_with_mnemonic (NULL, _("MADE IN CHINA"));
  gtk_widget_show (rb5);
  gtk_container_add (GTK_CONTAINER (eventbox66), rb5);
  gtk_widget_set_size_request (rb5, 136, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb5), rb1_group);
  rb1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb5));

  eventbox67 = gtk_event_box_new ();
  gtk_widget_show (eventbox67);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox67, 232, 472);
  gtk_widget_set_size_request (eventbox67, 208, 24);

  confmodf = gtk_check_button_new_with_mnemonic (_("confirmer la modification"));
  gtk_widget_show (confmodf);
  gtk_container_add (GTK_CONTAINER (eventbox67), confmodf);
  gtk_widget_set_size_request (confmodf, 208, 24);

  eventbox73 = gtk_event_box_new ();
  gtk_widget_show (eventbox73);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox73, 240, 200);
  gtk_widget_set_size_request (eventbox73, 400, 25);

  labelverifexiste = gtk_label_new ("");
  gtk_widget_show (labelverifexiste);
  gtk_container_add (GTK_CONTAINER (eventbox73), labelverifexiste);
  gtk_widget_set_size_request (labelverifexiste, 400, 25);

  eventbox78 = gtk_event_box_new ();
  gtk_widget_show (eventbox78);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox78, 8, 8);
  gtk_widget_set_size_request (eventbox78, 96, 48);

  buttonannulerm = gtk_button_new ();
  gtk_widget_show (buttonannulerm);
  gtk_container_add (GTK_CONTAINER (eventbox78), buttonannulerm);
  gtk_widget_set_size_request (buttonannulerm, 96, 48);

  annulerm = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (annulerm);
  gtk_container_add (GTK_CONTAINER (buttonannulerm), annulerm);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (annulerm), hbox7);

  image10 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  label = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label);
  gtk_box_pack_start (GTK_BOX (hbox7), label, FALSE, FALSE, 0);

  eventbox79 = gtk_event_box_new ();
  gtk_widget_show (eventbox79);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox79, 512, 144);
  gtk_widget_set_size_request (eventbox79, 128, 37);

  verifierexiste = gtk_button_new ();
  gtk_widget_show (verifierexiste);
  gtk_container_add (GTK_CONTAINER (eventbox79), verifierexiste);
  gtk_widget_set_size_request (verifierexiste, 128, 37);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (verifierexiste), alignment17);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox15);

  image22 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox15), image22, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("v\303\251rification"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox15), label42, FALSE, FALSE, 0);

  eventbox85 = gtk_event_box_new ();
  gtk_widget_show (eventbox85);
  gtk_fixed_put (GTK_FIXED (fixed2), eventbox85, 512, 488);
  gtk_widget_set_size_request (eventbox85, 160, 61);

  confirmerm = gtk_button_new ();
  gtk_widget_show (confirmerm);
  gtk_container_add (GTK_CONTAINER (eventbox85), confirmerm);
  gtk_widget_set_size_request (confirmerm, 160, 61);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_container_add (GTK_CONTAINER (confirmerm), eventbox34);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (eventbox34), alignment7);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  eventbox84 = gtk_event_box_new ();
  gtk_widget_show (eventbox84);
  gtk_box_pack_start (GTK_BOX (hbox6), eventbox84, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label27);
  gtk_container_add (GTK_CONTAINER (eventbox84), label27);

  image7 = create_pixmap (modifier_capteur, "1.png");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed2), image7, 0, 0);
  gtk_widget_set_size_request (image7, 832, 608);

  g_signal_connect ((gpointer) rb1, "toggled",
                    G_CALLBACK (on_rb1_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb2, "toggled",
                    G_CALLBACK (on_rb2_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb3, "toggled",
                    G_CALLBACK (on_rb3_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb4, "toggled",
                    G_CALLBACK (on_rb4_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb5, "toggled",
                    G_CALLBACK (on_rb5_toggled),
                    NULL);
  g_signal_connect ((gpointer) confmodf, "toggled",
                    G_CALLBACK (on_confmodf_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonannulerm, "clicked",
                    G_CALLBACK (on_buttonannulerm_clicked),
                    NULL);
  g_signal_connect ((gpointer) verifierexiste, "clicked",
                    G_CALLBACK (on_verifierexiste_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirmerm, "clicked",
                    G_CALLBACK (on_confirmerm_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_capteur, modifier_capteur, "modifier_capteur");
  GLADE_HOOKUP_OBJECT (modifier_capteur, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (modifier_capteur, entryidm, "entryidm");
  GLADE_HOOKUP_OBJECT (modifier_capteur, entryvaleurm, "entryvaleurm");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox26, "eventbox26");
  GLADE_HOOKUP_OBJECT (modifier_capteur, labeldatem, "labeldatem");
  GLADE_HOOKUP_OBJECT (modifier_capteur, spinbuttonjourm, "spinbuttonjourm");
  GLADE_HOOKUP_OBJECT (modifier_capteur, spinbuttonmoism, "spinbuttonmoism");
  GLADE_HOOKUP_OBJECT (modifier_capteur, spinbuttonanneem, "spinbuttonanneem");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox27, "eventbox27");
  GLADE_HOOKUP_OBJECT (modifier_capteur, labelvaleurm, "labelvaleurm");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox28, "eventbox28");
  GLADE_HOOKUP_OBJECT (modifier_capteur, labelidm, "labelidm");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox29, "eventbox29");
  GLADE_HOOKUP_OBJECT (modifier_capteur, labelmodifiercapteur, "labelmodifiercapteur");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox30, "eventbox30");
  GLADE_HOOKUP_OBJECT (modifier_capteur, labelanneem, "labelanneem");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox31, "eventbox31");
  GLADE_HOOKUP_OBJECT (modifier_capteur, labelmoism, "labelmoism");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox32, "eventbox32");
  GLADE_HOOKUP_OBJECT (modifier_capteur, labeljourm, "labeljourm");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label29, "label29");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (modifier_capteur, labelaffichagem, "labelaffichagem");
  GLADE_HOOKUP_OBJECT (modifier_capteur, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox59, "eventbox59");
  GLADE_HOOKUP_OBJECT (modifier_capteur, labelmarquem, "labelmarquem");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox60, "eventbox60");
  GLADE_HOOKUP_OBJECT (modifier_capteur, comboboxm, "comboboxm");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox61, "eventbox61");
  GLADE_HOOKUP_OBJECT (modifier_capteur, labeltypem, "labeltypem");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox62, "eventbox62");
  GLADE_HOOKUP_OBJECT (modifier_capteur, rb1, "rb1");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox63, "eventbox63");
  GLADE_HOOKUP_OBJECT (modifier_capteur, rb2, "rb2");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox64, "eventbox64");
  GLADE_HOOKUP_OBJECT (modifier_capteur, rb3, "rb3");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox65, "eventbox65");
  GLADE_HOOKUP_OBJECT (modifier_capteur, rb4, "rb4");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox66, "eventbox66");
  GLADE_HOOKUP_OBJECT (modifier_capteur, rb5, "rb5");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox67, "eventbox67");
  GLADE_HOOKUP_OBJECT (modifier_capteur, confmodf, "confmodf");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox73, "eventbox73");
  GLADE_HOOKUP_OBJECT (modifier_capteur, labelverifexiste, "labelverifexiste");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox78, "eventbox78");
  GLADE_HOOKUP_OBJECT (modifier_capteur, buttonannulerm, "buttonannulerm");
  GLADE_HOOKUP_OBJECT (modifier_capteur, annulerm, "annulerm");
  GLADE_HOOKUP_OBJECT (modifier_capteur, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (modifier_capteur, image10, "image10");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label, "label");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox79, "eventbox79");
  GLADE_HOOKUP_OBJECT (modifier_capteur, verifierexiste, "verifierexiste");
  GLADE_HOOKUP_OBJECT (modifier_capteur, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (modifier_capteur, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (modifier_capteur, image22, "image22");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label42, "label42");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox85, "eventbox85");
  GLADE_HOOKUP_OBJECT (modifier_capteur, confirmerm, "confirmerm");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (modifier_capteur, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (modifier_capteur, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (modifier_capteur, image9, "image9");
  GLADE_HOOKUP_OBJECT (modifier_capteur, eventbox84, "eventbox84");
  GLADE_HOOKUP_OBJECT (modifier_capteur, label27, "label27");
  GLADE_HOOKUP_OBJECT (modifier_capteur, image7, "image7");

  return modifier_capteur;
}

GtkWidget*
create_ajouter_capteur (void)
{
  GtkWidget *ajouter_capteur;
  GtkWidget *fixed3;
  GtkObject *spinbuttonja_adj;
  GtkWidget *spinbuttonja;
  GtkObject *spinbuttonmoisa_adj;
  GtkWidget *spinbuttonmoisa;
  GtkObject *spinbuttonanneea_adj;
  GtkWidget *spinbuttonanneea;
  GtkWidget *entryvaleura;
  GtkWidget *entryida;
  GtkWidget *eventbox13;
  GtkWidget *labelvaleura;
  GtkWidget *eventbox14;
  GtkWidget *labeldatea;
  GtkWidget *eventbox15;
  GtkWidget *labelida;
  GtkWidget *eventbox16;
  GtkWidget *labeljoura;
  GtkWidget *eventbox17;
  GtkWidget *labelmoisa;
  GtkWidget *eventbox18;
  GtkWidget *labelanneea;
  GtkWidget *eventbox19;
  GtkWidget *labelAC;
  GtkWidget *eventbox21;
  GtkWidget *labelconfajout;
  GtkWidget *eventbox23;
  GtkWidget *buttonajoutc;
  GtkWidget *alignment6;
  GtkWidget *hbox5;
  GtkWidget *image8;
  GtkWidget *labelajou;
  GtkWidget *eventbox56;
  GtkWidget *labelmarquea;
  GtkWidget *eventbox57;
  GtkWidget *labeltypea;
  GtkWidget *eventbox58;
  GtkWidget *comboboxac;
  GtkWidget *eventbox68;
  GtkWidget *rb6;
  GSList *rb6_group = NULL;
  GtkWidget *eventbox69;
  GtkWidget *rb7;
  GtkWidget *eventbox70;
  GtkWidget *rb8;
  GtkWidget *eventbox71;
  GtkWidget *rb9;
  GtkWidget *eventbox72;
  GtkWidget *rb10;
  GtkWidget *eventbox80;
  GtkWidget *Annulera;
  GtkWidget *alignment18;
  GtkWidget *hbox16;
  GtkWidget *image23;
  GtkWidget *label43;
  GtkWidget *imageac;

  ajouter_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_capteur), _("ajouter"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (ajouter_capteur), fixed3);

  spinbuttonja_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttonja = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonja_adj), 1, 0);
  gtk_widget_show (spinbuttonja);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonja, 344, 272);
  gtk_widget_set_size_request (spinbuttonja, 60, 27);

  spinbuttonmoisa_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmoisa = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmoisa_adj), 1, 0);
  gtk_widget_show (spinbuttonmoisa);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonmoisa, 504, 272);
  gtk_widget_set_size_request (spinbuttonmoisa, 60, 27);

  spinbuttonanneea_adj = gtk_adjustment_new (2010, 2010, 2021, 1, 10, 10);
  spinbuttonanneea = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonanneea_adj), 1, 0);
  gtk_widget_show (spinbuttonanneea);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonanneea, 672, 272);
  gtk_widget_set_size_request (spinbuttonanneea, 72, 27);

  entryvaleura = gtk_entry_new ();
  gtk_widget_show (entryvaleura);
  gtk_fixed_put (GTK_FIXED (fixed3), entryvaleura, 280, 360);
  gtk_widget_set_size_request (entryvaleura, 152, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryvaleura), 8226);

  entryida = gtk_entry_new ();
  gtk_widget_show (entryida);
  gtk_fixed_put (GTK_FIXED (fixed3), entryida, 280, 104);
  gtk_widget_set_size_request (entryida, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryida), 8226);

  eventbox13 = gtk_event_box_new ();
  gtk_widget_show (eventbox13);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox13, 136, 352);
  gtk_widget_set_size_request (eventbox13, 80, 41);

  labelvaleura = gtk_label_new (_("Valeur"));
  gtk_widget_show (labelvaleura);
  gtk_container_add (GTK_CONTAINER (eventbox13), labelvaleura);
  gtk_widget_set_size_request (labelvaleura, 80, 41);

  eventbox14 = gtk_event_box_new ();
  gtk_widget_show (eventbox14);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox14, 128, 272);
  gtk_widget_set_size_request (eventbox14, 81, 40);

  labeldatea = gtk_label_new (_("Date"));
  gtk_widget_show (labeldatea);
  gtk_container_add (GTK_CONTAINER (eventbox14), labeldatea);
  gtk_widget_set_size_request (labeldatea, 81, 40);

  eventbox15 = gtk_event_box_new ();
  gtk_widget_show (eventbox15);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox15, 128, 96);
  gtk_widget_set_size_request (eventbox15, 96, 48);

  labelida = gtk_label_new (_("Identifiant"));
  gtk_widget_show (labelida);
  gtk_container_add (GTK_CONTAINER (eventbox15), labelida);
  gtk_widget_set_size_request (labelida, 96, 48);

  eventbox16 = gtk_event_box_new ();
  gtk_widget_show (eventbox16);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox16, 288, 272);
  gtk_widget_set_size_request (eventbox16, 49, 17);

  labeljoura = gtk_label_new (_("Jour"));
  gtk_widget_show (labeljoura);
  gtk_container_add (GTK_CONTAINER (eventbox16), labeljoura);
  gtk_widget_set_size_request (labeljoura, 49, 17);

  eventbox17 = gtk_event_box_new ();
  gtk_widget_show (eventbox17);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox17, 432, 272);
  gtk_widget_set_size_request (eventbox17, 49, 17);

  labelmoisa = gtk_label_new (_("Mois"));
  gtk_widget_show (labelmoisa);
  gtk_container_add (GTK_CONTAINER (eventbox17), labelmoisa);
  gtk_widget_set_size_request (labelmoisa, 49, 17);

  eventbox18 = gtk_event_box_new ();
  gtk_widget_show (eventbox18);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox18, 600, 272);
  gtk_widget_set_size_request (eventbox18, 49, 17);

  labelanneea = gtk_label_new (_("Annee"));
  gtk_widget_show (labelanneea);
  gtk_container_add (GTK_CONTAINER (eventbox18), labelanneea);
  gtk_widget_set_size_request (labelanneea, 49, 17);

  eventbox19 = gtk_event_box_new ();
  gtk_widget_show (eventbox19);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox19, 304, 24);
  gtk_widget_set_size_request (eventbox19, 224, 49);

  labelAC = gtk_label_new (_("Ajouter un capteur"));
  gtk_widget_show (labelAC);
  gtk_container_add (GTK_CONTAINER (eventbox19), labelAC);
  gtk_widget_set_size_request (labelAC, 224, 49);

  eventbox21 = gtk_event_box_new ();
  gtk_widget_show (eventbox21);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox21, 384, 472);
  gtk_widget_set_size_request (eventbox21, 304, 40);

  labelconfajout = gtk_label_new ("");
  gtk_widget_show (labelconfajout);
  gtk_container_add (GTK_CONTAINER (eventbox21), labelconfajout);
  gtk_widget_set_size_request (labelconfajout, 304, 40);

  eventbox23 = gtk_event_box_new ();
  gtk_widget_show (eventbox23);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox23, 600, 400);
  gtk_widget_set_size_request (eventbox23, 152, 53);

  buttonajoutc = gtk_button_new ();
  gtk_widget_show (buttonajoutc);
  gtk_container_add (GTK_CONTAINER (eventbox23), buttonajoutc);
  gtk_widget_set_size_request (buttonajoutc, 152, 53);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonajoutc), alignment6);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox5);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox5), image8, FALSE, FALSE, 0);

  labelajou = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (labelajou);
  gtk_box_pack_start (GTK_BOX (hbox5), labelajou, FALSE, FALSE, 0);

  eventbox56 = gtk_event_box_new ();
  gtk_widget_show (eventbox56);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox56, 128, 152);
  gtk_widget_set_size_request (eventbox56, 96, 41);

  labelmarquea = gtk_label_new (_("Marque"));
  gtk_widget_show (labelmarquea);
  gtk_container_add (GTK_CONTAINER (eventbox56), labelmarquea);
  gtk_widget_set_size_request (labelmarquea, 96, 41);

  eventbox57 = gtk_event_box_new ();
  gtk_widget_show (eventbox57);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox57, 128, 208);
  gtk_widget_set_size_request (eventbox57, 96, 41);

  labeltypea = gtk_label_new (_("Type"));
  gtk_widget_show (labeltypea);
  gtk_container_add (GTK_CONTAINER (eventbox57), labeltypea);
  gtk_widget_set_size_request (labeltypea, 96, 41);

  eventbox58 = gtk_event_box_new ();
  gtk_widget_show (eventbox58);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox58, 280, 208);
  gtk_widget_set_size_request (eventbox58, 200, 39);

  comboboxac = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxac);
  gtk_container_add (GTK_CONTAINER (eventbox58), comboboxac);
  gtk_widget_set_size_request (comboboxac, 200, 39);
  gtk_container_set_border_width (GTK_CONTAINER (comboboxac), 1);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxac), _("capteur_de_Mouvement"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxac), _("capteur_de_Fumee"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxac), _("capteur_de_Debit_deau"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxac), _("capteur_de_Temperature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxac), _("Balance"));

  eventbox68 = gtk_event_box_new ();
  gtk_widget_show (eventbox68);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox68, 248, 160);
  gtk_widget_set_size_request (eventbox68, 80, 24);

  rb6 = gtk_radio_button_new_with_mnemonic (NULL, _("CHERRY"));
  gtk_widget_show (rb6);
  gtk_container_add (GTK_CONTAINER (eventbox68), rb6);
  gtk_widget_set_size_request (rb6, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb6), rb6_group);
  rb6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb6));

  eventbox69 = gtk_event_box_new ();
  gtk_widget_show (eventbox69);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox69, 336, 160);
  gtk_widget_set_size_request (eventbox69, 80, 24);

  rb7 = gtk_radio_button_new_with_mnemonic (NULL, _("NERDO"));
  gtk_widget_show (rb7);
  gtk_container_add (GTK_CONTAINER (eventbox69), rb7);
  gtk_widget_set_size_request (rb7, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb7), rb6_group);
  rb6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb7));

  eventbox70 = gtk_event_box_new ();
  gtk_widget_show (eventbox70);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox70, 424, 160);
  gtk_widget_set_size_request (eventbox70, 136, 24);

  rb8 = gtk_radio_button_new_with_mnemonic (NULL, _("MICRO-EPSILON"));
  gtk_widget_show (rb8);
  gtk_container_add (GTK_CONTAINER (eventbox70), rb8);
  gtk_widget_set_size_request (rb8, 136, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb8), rb6_group);
  rb6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb8));

  eventbox71 = gtk_event_box_new ();
  gtk_widget_show (eventbox71);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox71, 568, 160);
  gtk_widget_set_size_request (eventbox71, 80, 24);

  rb9 = gtk_radio_button_new_with_mnemonic (NULL, _("BOSCH"));
  gtk_widget_show (rb9);
  gtk_container_add (GTK_CONTAINER (eventbox71), rb9);
  gtk_widget_set_size_request (rb9, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb9), rb6_group);
  rb6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb9));

  eventbox72 = gtk_event_box_new ();
  gtk_widget_show (eventbox72);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox72, 664, 160);
  gtk_widget_set_size_request (eventbox72, 136, 24);

  rb10 = gtk_radio_button_new_with_mnemonic (NULL, _("MADE IN CHINA"));
  gtk_widget_show (rb10);
  gtk_container_add (GTK_CONTAINER (eventbox72), rb10);
  gtk_widget_set_size_request (rb10, 136, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb10), rb6_group);
  rb6_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb10));

  eventbox80 = gtk_event_box_new ();
  gtk_widget_show (eventbox80);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox80, 8, 8);
  gtk_widget_set_size_request (eventbox80, 112, 37);

  Annulera = gtk_button_new ();
  gtk_widget_show (Annulera);
  gtk_container_add (GTK_CONTAINER (eventbox80), Annulera);
  gtk_widget_set_size_request (Annulera, 112, 37);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (Annulera), alignment18);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox16);

  image23 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox16), image23, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox16), label43, FALSE, FALSE, 0);

  imageac = create_pixmap (ajouter_capteur, "1.png");
  gtk_widget_show (imageac);
  gtk_fixed_put (GTK_FIXED (fixed3), imageac, 0, 0);
  gtk_widget_set_size_request (imageac, 840, 608);

  g_signal_connect ((gpointer) buttonajoutc, "clicked",
                    G_CALLBACK (on_buttonajoutc_clicked),
                    NULL);
  g_signal_connect ((gpointer) rb6, "toggled",
                    G_CALLBACK (on_rb6_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb7, "toggled",
                    G_CALLBACK (on_rb7_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb8, "toggled",
                    G_CALLBACK (on_rb8_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb9, "toggled",
                    G_CALLBACK (on_rb9_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb10, "toggled",
                    G_CALLBACK (on_rb10_toggled),
                    NULL);
  g_signal_connect ((gpointer) Annulera, "clicked",
                    G_CALLBACK (on_Annulera_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_capteur, ajouter_capteur, "ajouter_capteur");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, spinbuttonja, "spinbuttonja");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, spinbuttonmoisa, "spinbuttonmoisa");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, spinbuttonanneea, "spinbuttonanneea");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, entryvaleura, "entryvaleura");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, entryida, "entryida");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox13, "eventbox13");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, labelvaleura, "labelvaleura");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox14, "eventbox14");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, labeldatea, "labeldatea");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox15, "eventbox15");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, labelida, "labelida");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox16, "eventbox16");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, labeljoura, "labeljoura");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox17, "eventbox17");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, labelmoisa, "labelmoisa");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox18, "eventbox18");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, labelanneea, "labelanneea");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox19, "eventbox19");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, labelAC, "labelAC");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox21, "eventbox21");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, labelconfajout, "labelconfajout");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox23, "eventbox23");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, buttonajoutc, "buttonajoutc");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, image8, "image8");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, labelajou, "labelajou");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox56, "eventbox56");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, labelmarquea, "labelmarquea");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox57, "eventbox57");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, labeltypea, "labeltypea");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox58, "eventbox58");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, comboboxac, "comboboxac");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox68, "eventbox68");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, rb6, "rb6");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox69, "eventbox69");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, rb7, "rb7");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox70, "eventbox70");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, rb8, "rb8");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox71, "eventbox71");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, rb9, "rb9");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox72, "eventbox72");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, rb10, "rb10");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, eventbox80, "eventbox80");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, Annulera, "Annulera");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, image23, "image23");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, label43, "label43");
  GLADE_HOOKUP_OBJECT (ajouter_capteur, imageac, "imageac");

  return ajouter_capteur;
}

GtkWidget*
create_supprimer_capteur (void)
{
  GtkWidget *supprimer_capteur;
  GtkWidget *fixed4;
  GtkWidget *entryids;
  GtkWidget *eventbox36;
  GtkWidget *labelids;
  GtkWidget *eventbox38;
  GtkWidget *labelSC;
  GtkWidget *eventbox75;
  GtkWidget *supprimcapt;
  GtkWidget *eventbox82;
  GtkWidget *buttonannulerS;
  GtkWidget *eventbox81;
  GtkWidget *alignment10;
  GtkWidget *hbox9;
  GtkWidget *image13;
  GtkWidget *label34;
  GtkWidget *eventbox83;
  GtkWidget *buttonsuppc;
  GtkWidget *eventbox39;
  GtkWidget *alignment9;
  GtkWidget *hbox8;
  GtkWidget *image12;
  GtkWidget *labels;
  GtkWidget *images;

  supprimer_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_capteur), _("supprimercapteur"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (supprimer_capteur), fixed4);

  entryids = gtk_entry_new ();
  gtk_widget_show (entryids);
  gtk_fixed_put (GTK_FIXED (fixed4), entryids, 304, 216);
  gtk_widget_set_size_request (entryids, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryids), 8226);

  eventbox36 = gtk_event_box_new ();
  gtk_widget_show (eventbox36);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox36, 120, 208);
  gtk_widget_set_size_request (eventbox36, 112, 49);

  labelids = gtk_label_new (_("Identifiant"));
  gtk_widget_show (labelids);
  gtk_container_add (GTK_CONTAINER (eventbox36), labelids);
  gtk_widget_set_size_request (labelids, 112, 49);

  eventbox38 = gtk_event_box_new ();
  gtk_widget_show (eventbox38);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox38, 304, 24);
  gtk_widget_set_size_request (eventbox38, 217, 80);

  labelSC = gtk_label_new (_("Supprimer un capteur"));
  gtk_widget_show (labelSC);
  gtk_container_add (GTK_CONTAINER (eventbox38), labelSC);
  gtk_widget_set_size_request (labelSC, 217, 80);

  eventbox75 = gtk_event_box_new ();
  gtk_widget_show (eventbox75);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox75, 80, 344);
  gtk_widget_set_size_request (eventbox75, 264, 57);

  supprimcapt = gtk_label_new ("");
  gtk_widget_show (supprimcapt);
  gtk_container_add (GTK_CONTAINER (eventbox75), supprimcapt);
  gtk_widget_set_size_request (supprimcapt, 264, 57);

  eventbox82 = gtk_event_box_new ();
  gtk_widget_show (eventbox82);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox82, 16, 16);
  gtk_widget_set_size_request (eventbox82, 120, 53);

  buttonannulerS = gtk_button_new ();
  gtk_widget_show (buttonannulerS);
  gtk_container_add (GTK_CONTAINER (eventbox82), buttonannulerS);
  gtk_widget_set_size_request (buttonannulerS, 120, 53);

  eventbox81 = gtk_event_box_new ();
  gtk_widget_show (eventbox81);
  gtk_container_add (GTK_CONTAINER (buttonannulerS), eventbox81);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (eventbox81), alignment10);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox9);

  image13 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox9), image13, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox9), label34, FALSE, FALSE, 0);

  eventbox83 = gtk_event_box_new ();
  gtk_widget_show (eventbox83);
  gtk_fixed_put (GTK_FIXED (fixed4), eventbox83, 392, 344);
  gtk_widget_set_size_request (eventbox83, 170, 53);

  buttonsuppc = gtk_button_new ();
  gtk_widget_show (buttonsuppc);
  gtk_container_add (GTK_CONTAINER (eventbox83), buttonsuppc);
  gtk_widget_set_size_request (buttonsuppc, 170, 53);

  eventbox39 = gtk_event_box_new ();
  gtk_widget_show (eventbox39);
  gtk_container_add (GTK_CONTAINER (buttonsuppc), eventbox39);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (eventbox39), alignment9);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox8);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox8), image12, FALSE, FALSE, 0);

  labels = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (labels);
  gtk_box_pack_start (GTK_BOX (hbox8), labels, FALSE, FALSE, 0);

  images = create_pixmap (supprimer_capteur, "1.png");
  gtk_widget_show (images);
  gtk_fixed_put (GTK_FIXED (fixed4), images, 0, 0);
  gtk_widget_set_size_request (images, 728, 504);

  g_signal_connect ((gpointer) buttonannulerS, "clicked",
                    G_CALLBACK (on_buttonannulerS_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsuppc, "clicked",
                    G_CALLBACK (on_buttonsuppc_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_capteur, supprimer_capteur, "supprimer_capteur");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, entryids, "entryids");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, eventbox36, "eventbox36");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, labelids, "labelids");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, eventbox38, "eventbox38");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, labelSC, "labelSC");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, eventbox75, "eventbox75");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, supprimcapt, "supprimcapt");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, eventbox82, "eventbox82");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, buttonannulerS, "buttonannulerS");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, eventbox81, "eventbox81");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, image13, "image13");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, label34, "label34");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, eventbox83, "eventbox83");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, buttonsuppc, "buttonsuppc");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, eventbox39, "eventbox39");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, image12, "image12");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, labels, "labels");
  GLADE_HOOKUP_OBJECT (supprimer_capteur, images, "images");

  return supprimer_capteur;
}

GtkWidget*
create_rechercher_capteur (void)
{
  GtkWidget *rechercher_capteur;
  GtkWidget *fixed6;
  GtkWidget *entryidr;
  GtkWidget *eventbox42;
  GtkWidget *labelaffi_capt_r;
  GtkWidget *eventbox43;
  GtkWidget *buttonrc;
  GtkWidget *alignment11;
  GtkWidget *hbox10;
  GtkWidget *image17;
  GtkWidget *labelr;
  GtkWidget *eventbox44;
  GtkWidget *labelRC;
  GtkWidget *eventbox45;
  GtkWidget *labelidr;
  GtkWidget *eventbox47;
  GtkWidget *imager1;
  GtkWidget *eventbox90;
  GtkWidget *buttonanuulerR;
  GtkWidget *alignment19;
  GtkWidget *hbox17;
  GtkWidget *image24;
  GtkWidget *label44;
  GtkWidget *imager;

  rechercher_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (rechercher_capteur), _("rechercher"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (rechercher_capteur), fixed6);

  entryidr = gtk_entry_new ();
  gtk_widget_show (entryidr);
  gtk_fixed_put (GTK_FIXED (fixed6), entryidr, 384, 200);
  gtk_widget_set_size_request (entryidr, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidr), 8226);

  eventbox42 = gtk_event_box_new ();
  gtk_widget_show (eventbox42);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox42, 224, 352);
  gtk_widget_set_size_request (eventbox42, 488, 72);

  labelaffi_capt_r = gtk_label_new ("");
  gtk_widget_show (labelaffi_capt_r);
  gtk_container_add (GTK_CONTAINER (eventbox42), labelaffi_capt_r);
  gtk_widget_set_size_request (labelaffi_capt_r, 488, 72);

  eventbox43 = gtk_event_box_new ();
  gtk_widget_show (eventbox43);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox43, 528, 256);
  gtk_widget_set_size_request (eventbox43, 168, 45);

  buttonrc = gtk_button_new ();
  gtk_widget_show (buttonrc);
  gtk_container_add (GTK_CONTAINER (eventbox43), buttonrc);
  gtk_widget_set_size_request (buttonrc, 168, 45);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonrc), alignment11);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox10);

  image17 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox10), image17, FALSE, FALSE, 0);

  labelr = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (labelr);
  gtk_box_pack_start (GTK_BOX (hbox10), labelr, FALSE, FALSE, 0);

  eventbox44 = gtk_event_box_new ();
  gtk_widget_show (eventbox44);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox44, 304, 56);
  gtk_widget_set_size_request (eventbox44, 264, 80);

  labelRC = gtk_label_new (_("Rechercher un capteur"));
  gtk_widget_show (labelRC);
  gtk_container_add (GTK_CONTAINER (eventbox44), labelRC);
  gtk_widget_set_size_request (labelRC, 264, 80);

  eventbox45 = gtk_event_box_new ();
  gtk_widget_show (eventbox45);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox45, 216, 200);
  gtk_widget_set_size_request (eventbox45, 120, 33);

  labelidr = gtk_label_new (_("Identifiant"));
  gtk_widget_show (labelidr);
  gtk_container_add (GTK_CONTAINER (eventbox45), labelidr);
  gtk_widget_set_size_request (labelidr, 120, 33);

  eventbox47 = gtk_event_box_new ();
  gtk_widget_show (eventbox47);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox47, 712, 0);
  gtk_widget_set_size_request (eventbox47, 160, 296);

  imager1 = create_pixmap (rechercher_capteur, "search_5ryql94k.gif");
  gtk_widget_show (imager1);
  gtk_container_add (GTK_CONTAINER (eventbox47), imager1);
  gtk_widget_set_size_request (imager1, 160, 296);

  eventbox90 = gtk_event_box_new ();
  gtk_widget_show (eventbox90);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox90, 8, 8);
  gtk_widget_set_size_request (eventbox90, 128, 37);

  buttonanuulerR = gtk_button_new ();
  gtk_widget_show (buttonanuulerR);
  gtk_container_add (GTK_CONTAINER (eventbox90), buttonanuulerR);
  gtk_widget_set_size_request (buttonanuulerR, 128, 37);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonanuulerR), alignment19);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox17);

  image24 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox17), image24, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox17), label44, FALSE, FALSE, 0);

  imager = create_pixmap (rechercher_capteur, "1.png");
  gtk_widget_show (imager);
  gtk_fixed_put (GTK_FIXED (fixed6), imager, 0, 0);
  gtk_widget_set_size_request (imager, 872, 504);

  g_signal_connect ((gpointer) buttonrc, "clicked",
                    G_CALLBACK (on_buttonrc_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonanuulerR, "clicked",
                    G_CALLBACK (on_buttonanuulerR_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rechercher_capteur, rechercher_capteur, "rechercher_capteur");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, entryidr, "entryidr");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, eventbox42, "eventbox42");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, labelaffi_capt_r, "labelaffi_capt_r");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, eventbox43, "eventbox43");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, buttonrc, "buttonrc");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, image17, "image17");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, labelr, "labelr");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, eventbox44, "eventbox44");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, labelRC, "labelRC");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, eventbox45, "eventbox45");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, labelidr, "labelidr");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, eventbox47, "eventbox47");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, imager1, "imager1");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, eventbox90, "eventbox90");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, buttonanuulerR, "buttonanuulerR");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, image24, "image24");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, label44, "label44");
  GLADE_HOOKUP_OBJECT (rechercher_capteur, imager, "imager");

  return rechercher_capteur;
}

